package v7

// 和风天气支持的语言代码常量
const (
	Arabic             = "ar"
	Bengali            = "bn"
	Czech              = "cs"
	Dutch              = "nl"
	English            = "eb"
	Estonian           = "et"
	Filipino           = "fil"
	Finnish            = "fi"
	French             = "fr"
	German             = "de"
	Greek              = "el"
	Hebrew             = "he"
	Hindi              = "hi"
	Icelandic          = "is"
	Indonesian         = "id"
	Italian            = "it"
	Japanese           = "ja"
	Korean             = "ko"
	Latin              = "la"
	Malay              = "ms"
	Norwegian          = "nb"
	Polish             = "pl"
	Portuguese         = "pt"
	Russian            = "ru"
	SimplifiedChinese  = "zh-hans"
	Spanish            = "es"
	Swedish            = "sv"
	Thai               = "th"
	TraditionalChinese = "zh-hant"
	Turkish            = "tr"
	Vietnamese         = "vi"
)
